### ISSUE TITLE
Wrong Repo Reference in License

### ISSUE THREAD

**Issue by SirNate0** [V1EngineeringInc/MPCNC_Primo#3]
The License in the Readme seems to reference the [Tool Mounts](https://github.com/V1EngineeringInc/MPCNC_Primo_Tool_Mounts) repository rather than the MPCNC_Primo one.

> Mostly Printed CNC Tool Mounts by [V1 Engineering Inc](https://www.v1engineering.com/) is licensed under a [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License](http://creativecommons.org/licenses/by-nc-sa/4.0/).

**Comment by V1EngineeringInc** [comment]
Thank you! I will fix it now.

(copy and pasted it a bunch that day)
