### ISSUE TITLE
Where can i find the STEP or Solid source files for the MPCNC?

### ISSUE THREAD

**Issue by X3msnake** [V1EngineeringInc/MPCNC_Primo#5]
I checked thinguiverse, github and prusa and i do not see any step files shared anywhere.
Would like to modify the machine to my needs and a STL is not a design file.

Best wishes
V

**Comment by V1EngineeringInc** [comment]
The source files are not shared, this is not fully open source.

**Comment by X3msnake** [comment]
https://blog.patshead.com/2019/09/my-thought-on-open-source-hardware.html
